import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/stylesheets/globals.css';
import localFont from 'next/font/local';

const customFont = localFont({
    src: [
        {
            path: '../public/fonts/quentin.ttf',
            weight: '400',
        },
    ],
    variable: '--font-quentin',
});

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Advance Beauty',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${montserrat.className} ${customFont.variable}`}>
            <body>
                {children}
            </body>
        </html>
    );
}
