import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/stylesheets/globals.css';
import localFont from 'next/font/local';
import ScrollToTop from '@/components/ui/features/ScrollToTop';
import { WhatsAppSolid } from '@/public/svgs';

const customFont = localFont({
    src: [
        {
            path: '../public/fonts/quentin.ttf',
            weight: '400',
        },
    ],
    variable: '--font-quentin',
});

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Advance Beauty',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${montserrat.className} ${customFont.variable}`}>
            <body>
                <div className="fixed bottom-24 lg:bottom-10 right-3 cursor-pointer flex flex-col gap-3 z-50">
                    <ScrollToTop />
                    <a href={`https://api.whatsapp.com/send?phone=%2B918826207080`} target="_blank" rel="noopener noreferrer" className="">
                        <WhatsAppSolid height="2.5rem" width="2.5rem" fillColor="#FF5956" strokeWidth="0" strokeColor="currentColor"/>
                    </a>
                </div>
                {children}
            </body>
        </html>
    );
}
